# Generated by Django 3.2.25 on 2025-01-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card_course_enrollment_lesson_listofusercourse_payment_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
